/**
 * explore.spec.ts
 *
 * Auto-generated by AIV Explorer.
 * Re-generate with: npm run generate:explore
 *
 * Generated : 2026-04-22T11:55:39.784Z
 * Sections  : 33
 * Base URL  : https://aiv.test.oneaiv.com:8086/aiv/
 */

import { test, expect } from '@playwright/test';

const BASE_URL = 'https://aiv.test.oneaiv.com:8086/aiv/';
const USERNAME = 'Admin';
const PASSWORD = 'Ganesh04';

test.describe('AIV Application - Full Feature Exploration', () => {

  test.beforeEach(async ({ page }) => {
    await page.goto(BASE_URL, { waitUntil: 'networkidle' });
    await page.waitForSelector("input[name='username']", { timeout: 15000 });
    await page.fill("input[name='username']", USERNAME);
    await page.fill("input[name='password']", PASSWORD);
    await page.click("button:has-text('Login')");
    await page.waitForSelector("input[placeholder='Search files and folders in All sections']", { timeout: 30000 });
  });

  test('List View', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Visualization/GridDashboard', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify URL contains the dashboard path (this section is a view mode of the dashboard)
    await expect(page).toHaveURL(/GridDashboard/i);
    await page.screenshot({ path: 'screenshots/list-view.png', fullPage: true });
  });

  test('Open in new tab', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Visualization/GridDashboard', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // This is a dashboard action, not a separate page — verify dashboard loaded
    await expect(page).toHaveURL(/GridDashboard/i);
    await page.screenshot({ path: 'screenshots/open-in-new-tab.png', fullPage: true });
  });

  test('Reports', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Documents/Reports', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // No interactive elements detected — verify URL only
    await expect(page).toHaveURL(/reports/i);
    await page.screenshot({ path: 'screenshots/reports.png', fullPage: true });
  });

  test('Merge Reports', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Documents/MergeReports', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // No interactive elements detected — verify URL only
    await expect(page).toHaveURL(/merge.*reports/i);
    await page.screenshot({ path: 'screenshots/merge-reports.png', fullPage: true });
  });

  test('Shared Resource', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Documents/SharedResources', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // No interactive elements detected — verify URL only
    await expect(page).toHaveURL(/shared.*resource/i);
    await page.screenshot({ path: 'screenshots/shared-resource.png', fullPage: true });
  });

  test('Quick Run', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Documents/QuickRun', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify the 'Create' button is visible
    await expect(page.getByRole('button', { name: 'Create' })).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/quick-run.png', fullPage: true });
  });

  test('Report Bursting', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/reportmap', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify the 'Select Report Mapping' input is visible
    await expect(page.getByPlaceholder('Select Report Mapping')).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/report-bursting.png', fullPage: true });
  });

  test('Group Report', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/groupReport', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify the 'Next' button is visible
    await expect(page.getByRole('button', { name: 'Next' })).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/group-report.png', fullPage: true });
  });

  test('Datasource', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/MasterData/Datasource', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify the 'Create' button is visible — use exact:true to avoid strict mode violation
    await expect(page.getByRole('button', { name: 'Create', exact: true }).first()).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/datasource.png', fullPage: true });
  });

  test('Datasets', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/MasterData/Datasets', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // No interactive elements detected — verify URL only
    await expect(page).toHaveURL(/datasets/i);
    await page.screenshot({ path: 'screenshots/datasets.png', fullPage: true });
  });

  test('Group Dataset', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/groupDataset', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify the 'Next' button is visible
    await expect(page.getByRole('button', { name: 'Next' })).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/group-dataset.png', fullPage: true });
  });

  test('Parameters', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/MasterData/Parameters', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify the 'Create' button is visible
    await expect(page.getByRole('button', { name: 'Create' })).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/parameters.png', fullPage: true });
  });

  test('Webhook', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/MasterData/webhook', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify the 'Create Webhook' button is visible
    await expect(page.getByRole('button', { name: 'Create Webhook' })).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/webhook.png', fullPage: true });
  });

  test('Notifications', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Request/Notifications', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify the 'Delete' button is visible
    await expect(page.getByRole('button', { name: 'Delete' })).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/notifications.png', fullPage: true });
  });

  test('Requests', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Request/Request', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify the 'Filter' button is visible
    await expect(page.getByRole('button', { name: 'Filter' })).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/requests.png', fullPage: true });
  });

  test('Alerts', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Request/Alerts', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // No interactive elements detected — verify URL only
    await expect(page).toHaveURL(/alerts/i);
    await page.screenshot({ path: 'screenshots/alerts.png', fullPage: true });
  });

  test('Alert Reports', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Request/AlertsX', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify a data table is rendered
    await expect(page.locator('table').first()).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/alert-reports.png', fullPage: true });
  });

  test('Repository', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Administration/Repository', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // No interactive elements detected — verify URL only
    await expect(page).toHaveURL(/repository/i);
    await page.screenshot({ path: 'screenshots/repository.png', fullPage: true });
  });

  test('Departments', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Administration/Department', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify the 'Create' button is visible
    await expect(page.getByRole('button', { name: 'Create' })).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/departments.png', fullPage: true });
  });

  test('Users', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Administration/Users', { waitUntil: 'networkidle', timeout: 60000 });
    // Confirm app shell is loaded — extended timeout for slow page
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 30000 });
    // Verify the 'Create User' button is visible
    await expect(page.getByRole('button', { name: 'Create User' })).toBeVisible({ timeout: 15000 });
    await page.screenshot({ path: 'screenshots/users.png', fullPage: true });
  });

  test('Roles', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Administration/Roles', { waitUntil: 'domcontentloaded', timeout: 60000 });
    // Confirm app shell is loaded — extended timeout for slow page
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 30000 });
    // Verify the 'Create' button is visible — use .first() to avoid strict mode violation
    await expect(page.getByRole('button', { name: 'Create', exact: true }).first()).toBeVisible({ timeout: 15000 });
    await page.screenshot({ path: 'screenshots/roles.png', fullPage: true });
  });

  test('Email Users', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Administration/EmailUsers', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify the 'Upload' button is visible
    await expect(page.getByRole('button', { name: 'Upload' })).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/email-users.png', fullPage: true });
  });

  test('File Types', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Administration/FileTypes', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify the 'Create' button is visible
    await expect(page.getByRole('button', { name: 'Create' })).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/file-types.png', fullPage: true });
  });

  test('AIV Configuration', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Administration/AivConfig', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify the 'Session timeout in minutes' input — use .first() to avoid strict mode violation (duplicate inputs)
    await expect(page.getByPlaceholder('Session timeout in minutes').first()).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/aiv-configuration.png', fullPage: true });
  });

  test('License', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Administration/License', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify the 'New Licence' button is visible
    await expect(page.getByRole('button', { name: 'New Licence' })).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/license.png', fullPage: true });
  });

  test('Dynamic Message', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Documents/Messages', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify the 'Create' button is visible
    await expect(page.getByRole('button', { name: 'Create' })).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/dynamic-message.png', fullPage: true });
  });

  test('Annotations', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Annotation', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify the annotation tree is rendered (mat-tree is the annotations list)
    await expect(page.locator('mat-tree, mat-nested-tree-node').first()).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/annotations.png', fullPage: true });
  });

  test('Control Panel', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/controlpanel', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // No interactive elements detected — verify URL only
    await expect(page).toHaveURL(/control.*panel/i);
    await page.screenshot({ path: 'screenshots/control-panel.png', fullPage: true });
  });

  test('Dashboard Internationalization', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/internationalization', { waitUntil: 'domcontentloaded', timeout: 60000 });
    // Confirm app shell is loaded — extended timeout, this page is slow after long test runs
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 30000 });
    // Verify URL confirms we are on the internationalization page
    await expect(page).toHaveURL(/internationalization/i);
    await page.screenshot({ path: 'screenshots/dashboard-internationalization.png', fullPage: true });
  });

  test('External APP', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/Visualization/GridExternalApp', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify the 'Upload' button is visible
    await expect(page.getByRole('button', { name: 'Upload' })).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/external-app.png', fullPage: true });
  });

  test('Api Token', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/ApiTokens', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify the 'Create API token' button is visible
    await expect(page.getByRole('button', { name: 'Create API token' })).toBeVisible({ timeout: 10000 });
    await page.screenshot({ path: 'screenshots/api-token.png', fullPage: true });
  });

  test('Connected APPS', async ({ page }) => {
    await page.goto('https://aiv.test.oneaiv.com:8086/aiv/connected-app', { waitUntil: 'networkidle', timeout: 30000 });
    // Confirm app shell is loaded
    await expect(page.getByPlaceholder('Search files and folders in All sections')).toBeVisible({ timeout: 15000 });
    // Verify URL — actual path is /connected-app (not /connected-apps)
    await expect(page).toHaveURL(/connected-app/i);
    await page.screenshot({ path: 'screenshots/connected-apps.png', fullPage: true });
  });

  test('AIVHUB Documentation', async ({ page }) => {
    // This is an external documentation site — test it separately from the app shell
    await page.goto('https://v6.docs.aivhub.com/', { waitUntil: 'networkidle', timeout: 30000 });
    // Verify the external docs site loaded (no AIV app shell here)
    await expect(page).toHaveURL(/docs\.aivhub\.com/i);
    await page.screenshot({ path: 'screenshots/aivhub-documentation.png', fullPage: true });
  });

});
